libs:
	g++ -fPIC -shared -std=c++11 -o libprefixtrie.o -Iprefixtrie -O3 prefixtrie/prefixtrie.cpp
	g++ -fPIC -shared -std=c++11 -o libbtree.o -Ibinarytree -O3 binarytree/binarytree.cpp
	g++ -fPIC -shared -std=c++11 -o libsort.o -Isorting -O3 sorting/quicksort.cpp sorting/selection.cpp sorting/bubblesort.cpp
